### PR TITLE
Starting by tidying up the Targets table

### PR DESCRIPTION
**Pull request by simaob**
* removed target_scopes table;
* added model to handle target's scopes like tags;
* small tweak in that form's order;

### CODE REVIEW

**Comment by tsubik** [comment]
:eyes:

**Comment by tsubik** [comment]
I haven't checked import/export though

**Comment by tsubik** [comment]
Maybe upload test could be updated to check if scopes are correctly created.

**Comment by tsubik** [comment]
Actually, nvm, could be done later. I think there is a task to refactor data uploads test. That would be anti-stress, leisure task, can pick it up next week.

**Comment by simaob** [comment]
Yeah, that works. I'm trying to add the imports, but it's taking longer than I would've hoped. But it's getting there.

**Comment by tsubik** [comment]
Yeah, half of import test are checking the data, but this one wasn't so no time to rewrite it now.

**Pull request merged**
