### PR TITLE
Dropdown selector

### PR DESCRIPTION
**Pull request by aabdaab**
This PR implements Dropdown Selector along with the fuzzy search functionality.
For fuzzy search [fuse.js](https://fusejs.io/) library is used. The dropdown component is custom.
On option selection, we are redirected to the sector/company's corresponding page.
Dropdown was added to three pages:
* `/tpi/sectors/` - corresponds to `All sections` option
* `/tpi/sectors/#{sector}` - specific sector
* `/tpi/companies/#{company}` - specific company

32E68C01-E62A-4AE7-8543-C5450585A446

Screenshot 2019-11-18 at 09 10 29

### CODE REVIEW

**Comment by tsubik** [comment]
Nice! I'm on it.

**Comment by tsubik** [comment]
I see that on your screenshots @aabdaab the dropdown has a good width.

**Comment by aabdaab** [comment]
thanks for the review 🙏 i'm on it

**Comment by aabdaab** [comment]
Done:
* Focus the input on opening the dropdown
* On hitting escape, close dropdown
* On click outside the search container, close dropdown
* Fix dropdown width

**Comment by aabdaab** [comment]
Added:
* Enter functionality - once you start typing and hit enter, user is redirected to the _first_ option
* Fix style for `No results` container

**Before:**
image

**After:**
image

* Fix that issue:
image

**Pull request merged**
