### PR TITLE
implement mobile versions of the Search page

### PR DESCRIPTION
**Pull request by batraisk**

### CODE REVIEW

**Comment by simaob** [comment]
I think I see a problem with closing a tag, once it's selected, the interface doesn't seem to update on mobile, but it does in the desktop version.

**Comment by simaob** [comment]
e.g.: selected Chile as a country, then click the little `x` and the tag stays there. Testing in responsive mode in Google Chrome.

**Comment by batraisk** [comment]
I checked and I did not have such a problem. I'll try to figure it out :)

**Comment by batraisk** [comment]
@simaob , I found the cause of the problem and fixed it.

**Pull request merged**
