### PR TITLE
Feature/update slugs

### PR DESCRIPTION
**Pull request by tsubik**
Change slugs whenever title changes for models with friendly_id module.

I added history for TPISectors and Companies as we are using slugs in the url there. Should be also done for Pages, but that's more work. Maybe instead of Dynamic routing we should have one route `get 'tpi/:page'? I could try that in this PR.

### CODE REVIEW

**Comment by simaob** [comment]
I think that's worth the try!

**Comment by tsubik** [comment]
Ok, After consideration, I think it's better to do smaller steps and do the Page refactor in another PR. Not sure when I can do that as I'm trying to figure out authorization and maybe there are higher priority stories.

**Comment by tsubik** [comment]
So, I'm marking this ready to review.

**Comment by tsubik** [comment]
Also worth to mention that if they already changed some titles, and slugs for them should be updated than we either have to update them manually or they have to change title to previous value and back to normal to get updated slug.

**Pull request merged**
