### PR TITLE
Feature/revisit core entities

### PR DESCRIPTION
**Pull request by tsubik**
Couple models updated

- Adding Keywords for Legislation and Litigation model, common tag system
- Adding Natural Hazards for Legislation
- Allow multiple values for Legislation framework, make Framework model manageable by admin
- Add INDC URL to Locations

Keywords and Natural Hazards are more open tags, which means a user can type and dynamically add new entries directly in the input.

### CODE REVIEW

**Comment by tsubik** [comment]
Forgot to mention would be great to do `bundle exec import:all`

**Comment by tsubik** [comment]
Those added in bulk will be added in input tag anyway, but I think that's a good idea to simplify Tag pages. Not sure if it is also worth removing `show` page, not much there. Probably `edit` page should be like a default one.

**Comment by tsubik** [comment]
I will do that in separate PR.

**Comment by simaob** [comment]
Makes sense, we don't need a show page for these type of resources! Cheers!

**Pull request merged**
