### PR TITLE
feature(frontend ui kit): configuration and scaffold

### PR DESCRIPTION
**Pull request by rapzo**

### CODE REVIEW

**Comment by rapzo** [comment]
test this please

**Comment by rapzo** [comment]
test this

**Comment by aabdaab** [comment]
could you rebase with develop? 🙏

**Comment by tsubik** [comment]
It would be great to merge this and build other features on top of it. Moving TPI public stuff into own namespace and with own controller, js packs and stylesheets as I started to implement in this PR https://github.com/Vizzuality/laws_and_pathways/pull/91/files

**Comment by rapzo** [comment]
Ok, rebased.
It didn't go well though...
But i'm working on it.
Do you have any ideas how we could isolate the CCLO styles? Because we cannot like have 2 bulma setups on launch.

**Comment by tsubik** [comment]
Only one bulma setup will be used for each site, depends on chosen layout, one for tpi, and one for cclow? Just we treat both sites separately, not sure, maybe we could pluck some shared styles into some sort of `/shared` folder?

**Comment by rapzo** [comment]
Different layouts! Yes! That'd do.
Gonna try to fix it, but feel free to press the button.
But a lot will break, visually, but i'll be working on sorting it out.

**Comment by tsubik** [comment]
It would be easier to recreate this branch on this repository, as I don't think I can push anything to your repository. Git complains about permissions.

**Comment by tsubik** [comment]
Ahh ok, then I'm going to merge this.

**Comment by tsubik** [comment]
Ahh, it's failing on CI.

**Comment by rapzo** [comment]
Forks inherit the same permissions as the original remote.
As they are automatically deleted if the original is as well.
You should be ok to push code to it, but i may be mistaken.
Anyways, what's failing is the :current_user thing i moved around in order to have public pages.

**Comment by tsubik** [comment]
Ok, I pushed that branch into this repository and will try to fix that issue.

**Comment by tsubik** [comment]
Almost there, going to move the home page to `tpi/` and I will add that base auth for staging too

**Comment by rapzo** [comment]
Thanks buddy!

**Comment by tsubik** [comment]
I'm also thinking that we should move TPI and CCLOW stylesheets and javascript into `javascript` folder (I know Rails ;P) to use webpacker instead of asset pipeline.

**Comment by tsubik** [comment]
Need to check if that is straightforward.

**Comment by rapzo** [comment]
That was the main issue I had with scaffolding and all (i don't know Rails that well hehe).
But, unless we go single-page-app, there isn't a real benefit from it, is it?
Wouldn't that make the CCLoW / TPI switch harder (creating two bundles, etc)?

**Comment by tsubik** [comment]
Hmm, I dunno, it's just a default way of doing things in rails now.

**Comment by tsubik** [comment]
asset pipeline must stay for that ActiveAdmin monster

**Comment by tsubik** [comment]
but I;m using both in ActiveAdmin actually, asset pipeline + webpacker because of es6

**Comment by tsubik** [comment]
Closing in favor of https://github.com/Vizzuality/laws_and_pathways/pull/93

**Pull request closed without merging**
