### PR TITLE
Feature/better cp assessment charts

### PR DESCRIPTION
**Pull request by tsubik**
Well almost done.
new-chart

I'm still missing that fancy labels for benchmark's areas and there is no this dropdown "Showing: Top emitters" and logic related to that. On loading I'm just taking the first 10 for now.

Initially I didn't have this "Apply changes" button, it dynamically changed the selected items. But there was a problem with "Add companies" button and this checkbox list changing position after any change ;].

### CODE REVIEW

**Comment by tsubik** [comment]
It's still draft. But could be tested already.

**Comment by tsubik** [comment]
Maybe we can merge this if it's fine and promise to deliver the rest of features later as I won't have much time tomorrow or today to finish the rest.

**Comment by simaob** [comment]
When on a company page this is not behaving as well, maybe because it's using the same component but not adjusted for that? I remove all the items from the legend and then I can't add them back.

Otherwise we could indeed merge. I need to review a little more closely later.

**Comment by tsubik** [comment]
I just hid the remove icon there.

**Comment by tsubik** [comment]
But, found bug when changing assessment. Chart is not rerendering :/

**Comment by tsubik** [comment]
Will take a look at this.

**Comment by tsubik** [comment]
Fixed! ;]

**Comment by simaob** [comment]
Thanks =)

**Comment by simaob** [comment]
Yes, now working. Only "final" remark on this version would be the extra white space under the chart on the Sector page. Which is not in the prod version, hopefully a small tweak and then it should be good as a first major improvement.

**Comment by tsubik** [comment]
I had to use react-highcharts directly, as Chartkick react wrapper wasn't working fine. I think we need to remove chartkick altogether and use react-highcharts everywhere.

**Comment by tsubik** [comment]
Ahh. Right. Good point, I missed that, I'm blind :man_facepalming:

**Comment by tsubik** [comment]
Done.

**Pull request merged**
