### PR TITLE
add cait emissions data

### PR DESCRIPTION
**Pull request by aabdaab**

### CODE REVIEW

**Comment by tsubik** [comment]
We also need to enable adding dataset in the code. I think we might change the code to get all datasets we have in the directory. With the use of extra metadata property in yaml file like `show` or `active` we can always disable any of them. `value_column` could be also moved to yaml file. `parse_value` function, hmm, that one could stay or also be in yaml file as text that will be executed  dynamically.

**Comment by simaob** [comment]
This is till WIP, right @edwardpmorris? until we get the data calculated in %?

**Comment by aabdaab** [comment]
this is ready ☝️ As Tomek suggested, we now get all the datasets from `map_data` folder and parse them if they have set `active: true` in the yaml metadata files.

**Comment by tsubik** [comment]
Great :+1:

**Pull request merged**
