### PR TITLE
update ruby version and fix travis

### PR DESCRIPTION
**Pull request by tsubik**

### CODE REVIEW

**Comment by tsubik** [comment]
Is the ruby update easy when deploying to the server?

**Comment by tsubik** [comment]
at least on cloud66  which is also using capistrano, updating ruby is not that pleasant (can't rollback later ;))

**Comment by simaob** [comment]
We are using rvm, so I might need to go to the server install that new version and only afterwards deploy it. Not sure if it requires a change to Apache config files too, as in my own server I had to change the ruby path

**Comment by tsubik** [comment]
Hopefully, it will be fine.

**Comment by simaob** [comment]
I added the rvm config string to the capistrano config.

**Pull request merged**
