### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by tsubik**
Bringing eslint to flash with errors and warnings.

Have to properly retest the website, as no integration tests.

### CODE REVIEW

**Comment by rapzo** [comment]
LGTM. Better wait for this than pushing my stuff in.

**Comment by tsubik** [comment]
Not sure how to set this up to fail on syntax errors only and compile with a warning for the rest.

**Comment by tsubik** [comment]
I clicked through admin panel and app and it seems it works.

**Comment by tsubik** [comment]
Ok, Lintstaged and husky added.

Also couple more yarn tasks, take a look at package.json

**Comment by tsubik** [comment]
Waiting for CI, and then merging.

**Pull request merged**
