### PR TITLE
Feature/latest information companies

### PR DESCRIPTION
**Pull request by simaob**
- Adds a couple of hints on the backend;
- Displays latest information block on the front end [WIP: still needs styling, can someone help me? =D ]

### CODE REVIEW

**Comment by aabdaab** [comment]
don't merge, I'm checking the styles :)

**Comment by tsubik** [comment]
ahh, I haven't, sorry

**Comment by aabdaab** [comment]
no worries, I'm on it

**Comment by aabdaab** [comment]
image

☝️ aligned with the rest of the company page

**Comment by simaob** [comment]
Screenshot 2019-12-16 at 19 07 43

**Comment by aabdaab** [comment]
Done:
screencast 2019-12-17 15-24-36

**Comment by simaob** [comment]
Thanks !=) the "read more" button shouldn't show up if the text is not long enough!

**Comment by aabdaab** [comment]
Ok, hid the button when the text is less or exactly three lines of text ☝️

**Comment by simaob** [comment]
Tks! =)

**Pull request merged**
