### PR TITLE
Feature/rapzo frontend ui kit

### PR DESCRIPTION
**Pull request by tsubik**
Moved https://github.com/Vizzuality/laws_and_pathways/pull/82 here and fixed tests. Hopefully, nothing got broken. @rapzo can you check if I everything is here? The default route is still admin dashboard, TPI is under `/tpi`

### CODE REVIEW

**Comment by simaob** [comment]
having a look too.

**Comment by tsubik** [comment]
I removed create Publications migration here so, if anyone will have a problem please do `rails db:reset`

**Comment by simaob** [comment]
I might've created these conflicts when I merge Marta's PR ... sorry

**Comment by rapzo** [comment]
Fixed. Should be harmless.

**Pull request merged**
