### PR TITLE
Keep default filter in the page's context

### PR DESCRIPTION
**Pull request by aabdaab**
Show the active filter based on the page we are on:
* when on a specific company page, the default filter is focused on `Filter by company`
* the rest is focused on `Filter by sector`

image

### CODE REVIEW

**Comment by aabdaab** [comment]
actually, when changing the filters at this point, it has no effect. maybe we should display the buttons only when the dropdown is open? @faustoperez wdyt?

**Comment by tsubik** [comment]
Or maybe clicking on "Filter by" should open the filter?

**Comment by tsubik** [comment]
changing_filter_by

**Comment by faustoperez** [comment]
Hey! The behaviour of the filtering box is as in the Invision prototype: https://projects.invisionapp.com/d/main#/console/18479580/384135669/preview

Clicking a `Filter by` button opens the filter, same as clicking the dropdown :)

**Comment by aabdaab** [comment]
fixed ☝️

**Pull request merged**
