### PR TITLE
Feature/change flag provider

### PR DESCRIPTION
**Pull request by simaob**
This PR updates the source of our flags, following from a recommendation by Fausto.
The updated flags are sourced from this repository: https://github.com/madebybowtie/FlagKit
I had to change the way we fetch the flags a little, because I get them directly from github using Oktokit.

### CODE REVIEW

**Comment by tsubik** [comment]
I was about to say that fixed rubocop offences.

**Comment by simaob** [comment]
I should code more, I forge these _details_

**Comment by tsubik** [comment]
One more thing I have to push here.

**Comment by tsubik** [comment]
EU and some other flag mapping. We also need International flag from somewhere and come up with code for this Supranational.

**Comment by simaob** [comment]
Thanks for the fixes. Fausto wanted this up so he can check which flags are missing, including international.

**Pull request merged**
