### PR TITLE
feature/cclow-tweaks_country_page

### PR DESCRIPTION
**Pull request by batraisk**

### CODE REVIEW

**Comment by aabdaab** [comment]
Thanks for the tweaks!
Regarding the logos in the header I think one thing is missing:
* LSE and Grantham logos in the header should link to their websites

**Comment by tsubik** [comment]
Lol, I was writing change request, but Simao was faster :D:D

**Comment by tsubik** [comment]
Didn't spot that there should be two separate logos, LSE and GRI. Gonna change that on develop.

**Comment by simaob** [comment]
😅 sorry! I saw the approval and didn't notice it was super recent. :D Tks!

**Pull request merged**
