### PR TITLE
Feature/cclow public downloads

### PR DESCRIPTION
**Pull request by tsubik**
Adding user public downloads for Legislations, Litigations and Climate Targets

Draft as two things could be improved:

- getting all legislations takes like 3 seconds on production data, in staging env. (at least on my machine, we could test that on staging too)
- some simple controller tests could be beneficial, didn't have time for them today

### CODE REVIEW

**Comment by tsubik** [comment]
In development evn. it's gonna take some time.

**Comment by simaob** [comment]
Given we don't have anything yet. We could merge and test on staging.

**Comment by simaob** [comment]
I mean, this is already better than the alternative =D and we can test it there.

**Comment by tsubik** [comment]
Ok!

**Comment by tsubik** [comment]
I'm gonna add some simple tests, and try to make things faster in the meantime.

**Pull request merged**
