### PR TITLE
Feature/cclow search filter

### PR DESCRIPTION
**Pull request by batraisk**

### CODE REVIEW

**Comment by simaob** [comment]
Are the filters hooked with the backend? They don't seem to be. Selecting a country doesn't filter the list of laws.

**Comment by tsubik** [comment]
I think that's my bad, I saw a region before, missed the country. So, that's filtering by region only.

**Comment by tsubik** [comment]
Taggin wasn't cleaned up before import, crap :/

image

**Comment by tsubik** [comment]
or the delimiter should be ';' or maybe there were 2 delimiters :P

**Comment by simaob** [comment]
Yes there's some crap in there. But most of mine look good. I can sort it out in the prod console later =D split and save. =)

**Comment by tsubik** [comment]
When filtering by Tags there should be `AND` not `OR` right?

**Comment by tsubik** [comment]
or maybe OR

**Comment by simaob** [comment]
that's always a tough question... @faustoperez what do you think? Tags are "has this AND that" or "has this OR that"?

**Comment by tsubik** [comment]
I see I must removed filter by geography.

**Comment by tsubik** [comment]
Countries should be `OR` I guess, so maybe tags too for consitency.

**Comment by tsubik** [comment]
I'm gonna bring back the `geography` filter @batraisk

**Comment by simaob** [comment]
Agreed, good thinking. OR it is.

**Comment by tsubik** [comment]
Done, geography should work.

**Comment by simaob** [comment]
Any other feedback? It looks pretty good to me! =)

**Comment by simaob** [comment]
Yes, sounds good! Can come in a separate PR!

**Comment by tsubik** [comment]
Let's how it works on staging.

**Comment by batraisk** [comment]
thank you @tsubik :)

**Pull request merged**
