### PR TITLE
[CCLOW] Style static pages according to UI kit

### PR DESCRIPTION
**Pull request by aabdaab**
[CCLOW] This PR adds more accurate styling to static pages according to UI kit:
- bullet lists;
- numbered lists;
- headings;
- bold;
- links

### CODE REVIEW

**Comment by simaob** [comment]
Not sure if this is like this on the UI kit, but I wonder if the bullets and numbered lists can be a little better aligned with the titles, they feel a bit out of position:

Screenshot 2020-02-27 at 13 39 07

**Comment by aabdaab** [comment]
On the designs they are outside of the grid: https://projects.invisionapp.com/d/main#/console/18784734/392404645/inspect
it does look a bit confusing though..

**Comment by simaob** [comment]
oh yes, you're right. Maybe that's just how it is! =) @faustoperez can you confirm? =) (see screenshot above).

**Comment by tsubik** [comment]
I agree that looks quite off

**Comment by faustoperez** [comment]
Yes, it is off on purpose on the designs (it's an actual recommendation on a Typography book I read), but please use the standard user agent margins, I don't have a hard preference and this seems to put people off :). Thanks!

**Comment by aabdaab** [comment]
Thanks for the input! I aligned the list items with the grid ☝️

**Pull request merged**
