### PR TITLE
stream publication files until we resolve that differently

### PR DESCRIPTION
**Pull request by tsubik**

### CODE REVIEW

**Comment by tsubik** [comment]
That is more a workaround than the real solution though.

**Comment by tsubik** [comment]
Gonna test alternative method of providing direct url to google cloud

**Comment by simaob** [comment]
Cheers, I'll wait for that!

**Comment by tsubik** [comment]
Hmm, I see some problems with just providing direct link to urls. When I attach a new file then the old one is removed from the bucket and the file with new id is uploaded (the old one is still available, weird, not sure for how long). But if someone shares the direct link and then the file will be switched, that's not gonna work as expected. Beside, I don't see filename to be saved as a metadata in google bucket so when downloading the file will have generated unique name, even without extension. That's not good too.

**Comment by tsubik** [comment]
I think we might go with streaming for now.

**Comment by tsubik** [comment]
We might need another controller for uploaded documents.

**Pull request merged**
