### PR TITLE
Add most recent additions in CCLOW search dropdown

### PR DESCRIPTION
**Pull request by aabdaab**
* Add most recent additions of laws, litigations and climate targets in the search dropdown
* Most recent = one month old
* Check against `created_at` attribute

### CODE REVIEW

**Comment by simaob** [comment]
When I open the dropdown it shows me the total for both of those "recent additions", will it only update if I type a search?

**Comment by aabdaab** [comment]
Because it's checking against the `created_at` and all of the records were created this month. Should we limit the number of the recent additions?

**Comment by simaob** [comment]
ah true, let's use something different, see my sorting on `app/services/api/latest_additions.rb`

**Comment by simaob** [comment]
Basing it on the events: https://github.com/Vizzuality/laws_and_pathways/blob/develop/app/services/api/latest_additions.rb#L17

**Comment by aabdaab** [comment]
Changed the recently added legislations and litigations to use the `LatestAdditions` service but in the future we should probably change it to pick up from `passed` and `started` scopes (legislation and litigation respectively)

**Pull request merged**
