### PR TITLE
Adds validation for geography_id in litigations

### PR DESCRIPTION
**Pull request by simaob**
Small PR to add validation for litigations' geography ID.
I'm not making bigger changes yet, because they still have some records without geography, they'll have to fix that first.

### CODE REVIEW

**Comment by simaob** [comment]
Yes, that's true. Maybe that's simpler?

**Comment by tsubik** [comment]
I think removing `optional` it tells right away that it cannot be null.

**Comment by tsubik** [comment]
Otherwise I would think that geography could be null, won't look at validations.

**Comment by simaob** [comment]
changed as discussed.

**Pull request merged**
