### PR TITLE
feature/cclow-sort-litigation

### PR DESCRIPTION
**Pull request by batraisk**

### CODE REVIEW

**Comment by tsubik** [comment]
I think the sort code should be moved into the query service. And we should sort by relevance if `q` param was provided. Otherwise we have things like on the screenshot

results-bad

**Comment by tsubik** [comment]
The first item on the list is not even properly visible.

The quick way to sort by relevance would be to add order by id scope to the model 
```
scope :with_id_order, ->(ids) {
    order = sanitize_sql_array(['array_position(ARRAY[?]::int[], id::int)', ids])
    order(order)
  }
```

and then memoize full text search id order and add `merge(order)` at the end of scope chains in query service.

```
      def order
        return scope.with_id_order(@full_text_result_ids) if defined?(@full_text_result_ids)

        # return default order here, so by the last event date
      end
```

**Comment by tsubik** [comment]
@batraisk could you please apply relevance order for Targets, Litigation, Legislations (I think as described above should work) and also default order by last event date.

**Comment by batraisk** [comment]
@tsubik , sure, no problem)

**Comment by batraisk** [comment]
@tsubik , @simaob , I updated the PR. Look please)

**Comment by tsubik** [comment]
Nice! @batraisk can you also add couple tests for testing the order. I'm not sure, those could be either query service tests or controller specs.

**Comment by batraisk** [comment]
@tsubik Done :)

**Pull request merged**
