### PR TITLE
Fix cp chart

### PR DESCRIPTION
**Pull request by tsubik**
Fixing CP chart problems.

### CODE REVIEW

**Comment by simaob** [comment]
I'm seeing something a little weird with the pledges:

Screenshot 2020-03-02 at 11 49 37
Screenshot 2020-03-02 at 11 49 46


When changing the assessment date, the pledges numbers are very different. Is this a data issue or could it be the chart misbehaving?

**Comment by tsubik** [comment]
The unit is different, the benchamark is different.

**Comment by tsubik** [comment]
It is always taking the right benchmark comparing benchmark release date with assessment publication date.

**Comment by tsubik** [comment]
Hmm, the unit is the same.

**Comment by simaob** [comment]
but am I seeing it wrong I see: gCO2/passenger-per-km

**Comment by simaob** [comment]
exactly! I had to triple check.

**Comment by tsubik** [comment]
Maybe they didn't update the unit?

**Comment by simaob** [comment]
I'm looking at local data, so might be just wrong data. I'll check on staging!

**Comment by tsubik** [comment]
On prod, there is also the same unit for both. Other unit, but there should be different units.

**Comment by simaob** [comment]
Maybe they haven't used the new feature of adjusting units ...

**Pull request merged**
