### PR TITLE
Adds a table with the latest comments to the dashboard

### PR DESCRIPTION
**Pull request by simaob**
First attempt. I still need to style the title :/

### CODE REVIEW

**Comment by simaob** [comment]
this code looks pretty ugly... should I create a view for this? any ideas? :D

**Comment by tsubik** [comment]
Maybe you could create some partial, and try to render it there `render 'some_partial', { comments: ActiveAdmin::Comment.all  }`

**Comment by tsubik** [comment]
I removed couple divs and added `panel` and it looks little better (the title)

**Comment by simaob** [comment]
Thanks, Tomasz!

**Pull request merged**
