### PR TITLE
improve(tpi): improvements to homepage

### PR DESCRIPTION
**Pull request by rapzo**

### CODE REVIEW

**Comment by rapzo** [comment]
Didn't touch on the partners piece because of what we previously talked: the assets displayed in the prototype are not set on stone, although some alignment is still missing. Let me know if you want me to patch anything there.

**Comment by aabdaab** [comment]
nice work 🙌
I'm thinking though, we're missing the navbar on the mobile; is it left for a different PR?
image

**Comment by rapzo** [comment]
Coming in a different PR.
I'm working on the search on top of the navbar so i took all out because there's no search on mobile ¯\_(ツ)_/¯
But we can leave it open or i can bring it back (although there's no banner on mobile too).
Your choice :-D

**Comment by aabdaab** [comment]
I actually meant the banner, about the navbar - no worries, in that next PR you're working on is fine

**Pull request merged**
